title: "Zih-Han Shen"
theme: minima
plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name/

header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/experience.md
